// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Beatmap struct {
	Beatmapid        sql.NullInt64  `json:"beatmapid"`
	Artist           sql.NullString `json:"artist"`
	Artistunicode    sql.NullString `json:"artistunicode"`
	Title            sql.NullString `json:"title"`
	Titleunicode     sql.NullString `json:"titleunicode"`
	Creator          sql.NullString `json:"creator"`
	Difficulty       sql.NullString `json:"difficulty"`
	Audio            sql.NullString `json:"audio"`
	Md5hash          sql.NullString `json:"md5hash"`
	File             sql.NullString `json:"file"`
	Rankedstatus     sql.NullString `json:"rankedstatus"`
	Lastmodifiedtime sql.NullInt64  `json:"lastmodifiedtime"`
	Totaltime        sql.NullInt64  `json:"totaltime"`
	Audiopreviewtime sql.NullInt64  `json:"audiopreviewtime"`
	Beatmapsetid     sql.NullInt64  `json:"beatmapsetid"`
	Source           sql.NullString `json:"source"`
	Tags             sql.NullString `json:"tags"`
	Lastplayed       sql.NullInt64  `json:"lastplayed"`
	Folder           sql.NullString `json:"folder"`
}

type Collection struct {
	Name    sql.NullString `json:"name"`
	Md5hash sql.NullString `json:"md5hash"`
}
