// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetBeatmapByHash(ctx context.Context, md5hash sql.NullString) (Beatmap, error)
	GetBeatmapCount(ctx context.Context) (int64, error)
	GetBeatmapSetCount(ctx context.Context) (int64, error)
	GetCollectionByName(ctx context.Context, arg GetCollectionByNameParams) ([]GetCollectionByNameRow, error)
	GetCollectionByOffset(ctx context.Context, arg GetCollectionByOffsetParams) ([]GetCollectionByOffsetRow, error)
	GetCollectionCountByName(ctx context.Context, name sql.NullString) (int64, error)
	GetRecentBeatmaps(ctx context.Context, arg GetRecentBeatmapsParams) ([]Beatmap, error)
	InsertBeatmap(ctx context.Context, arg InsertBeatmapParams) error
	InsertCollection(ctx context.Context, arg InsertCollectionParams) error
	SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]SearchArtistsRow, error)
	SearchBeatmaps(ctx context.Context, arg SearchBeatmapsParams) ([]Beatmap, error)
	SearchCollection(ctx context.Context, arg SearchCollectionParams) ([]SearchCollectionRow, error)
}

var _ Querier = (*Queries)(nil)
