// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetArtists(ctx context.Context, arg GetArtistsParams) ([]GetArtistsRow, error)
	GetBeatmapByHash(ctx context.Context, md5hash sql.NullString) (Beatmap, error)
	GetBeatmapCount(ctx context.Context) (int64, error)
	GetCollection(ctx context.Context, arg GetCollectionParams) ([]GetCollectionRow, error)
	GetCollectionByName(ctx context.Context, arg GetCollectionByNameParams) ([]GetCollectionByNameRow, error)
	GetCollectionCountByName(ctx context.Context, name sql.NullString) (int64, error)
	GetCollections(ctx context.Context, arg GetCollectionsParams) ([]GetCollectionsRow, error)
	GetRecentBeatmaps(ctx context.Context, arg GetRecentBeatmapsParams) ([]GetRecentBeatmapsRow, error)
	InsertBeatmap(ctx context.Context, arg InsertBeatmapParams) error
	InsertCollection(ctx context.Context, arg InsertCollectionParams) error
	SearchBeatmaps(ctx context.Context, arg SearchBeatmapsParams) ([]SearchBeatmapsRow, error)
}

var _ Querier = (*Queries)(nil)
