apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: osu-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: juli0n21/frontend-container:00ea48f4cc04369f765ca6bcdb5b7122f9931e67
        ports:
        - containerPort: 80
