apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: osu-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: juli0n21/frontend-container:52e93b772d63f2d1a06a4ca8155468f6cd33e353
        ports:
        - containerPort: 80
