apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: osu-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: proxy-container
        image: juli0n21/proxy-container:9cd067f250ca05ce6a5ded59ba9eefd89f7b4f07
        ports:
        - containerPort: 80
        volumeMounts:
        - name: proxy-data
          mountPath: /app/data
        env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: proxy-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: proxy-secrets
                  key: CLIENT_SECRET
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: proxy-secrets
                  key: REDIRECT_URI
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: proxy-secrets
                  key: HOST
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: proxy-secrets
                  key: PORT
      volumes:
      - name: proxy-data
        persistentVolumeClaim:
          claimName: proxy-data-pvc
